# Generated by Django 5.1.3 on 2024-11-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_franela', '0003_categoria_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='camisas/'),
        ),
    ]
